version: 2.1

# Define the jobs we want to run for this project
jobs:
  install:
    docker:
      - image: circleci/node:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: yarn
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: yarn build

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - install
      - build:
          requires:
            - install
